
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Tue Jul 02 15:26:19 EDT 2002
//----------------------------------------------------

package org.ephman.xml.dtd;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RBRACK = 3;
  public static final int UNCLOSED = 22;
  public static final int RPAREN = 14;
  public static final int QUOTED_NAME = 6;
  public static final int OR_BAR = 10;
  public static final int SLASH = 4;
  public static final int LBRACK = 2;
  public static final int SYNTAX = 19;
  public static final int PCDATA = 16;
  public static final int NAME = 7;
  public static final int LPAREN = 13;
  public static final int ATTLIST = 21;
  public static final int EQUALS = 5;
  public static final int COMMA = 15;
  public static final int EOF = 0;
  public static final int ANY = 11;
  public static final int CDATA = 17;
  public static final int ELEMENT = 20;
  public static final int error = 1;
  public static final int FIXED = 18;
  public static final int TEXT = 8;
  public static final int NAME_SYMBOL = 9;
  public static final int EMPTY = 12;
}

