
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Thu Jun 13 14:14:27 EDT 2002
//----------------------------------------------------

package org.ephman.xml;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACK_SLASH_NAME = 10;
  public static final int SLASH = 4;
  public static final int EOF = 0;
  public static final int UNCLOSED = 11;
  public static final int RBRACK = 3;
  public static final int error = 1;
  public static final int QUOTED_NAME = 6;
  public static final int TEXT = 8;
  public static final int LBRACK = 2;
  public static final int EQUALS = 5;
  public static final int LBRACK_NAME = 9;
  public static final int NAME = 7;
}

